on:
  push:
    branches:
      - master

name: Deploy to Production (S3)

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build
        id: build
        run: |
          echo npm install on `date`
          npm install
          echo npm build on `date`
          npm run build

      - name: Upload
        id: upload
        run: |
          echo Build completed on `date`
          echo Uploading s3
          lambdas=`cat lambdas-cd`
          for i in $lambdas; do aws s3 cp dist/latest.zip s3://lambdas/deploy/$i/latest.zip; done
          for i in $lambdas; do aws s3 cp dist/latest.zip s3://lambdas/deploy/$i/${{ github.sha }}.zip; done
